"""add order payment tracking columns

Revision ID: d0ad8423fdc2
Revises: 6128b789f9d7
Create Date: 2026-07-10 11:06:51.131740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ad8423fdc2'
down_revision: Union[str, Sequence[str], None] = '6128b789f9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tran_id', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_orders_tran_id'), 'orders', ['tran_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_tran_id'), table_name='orders')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'tran_id')
    # ### end Alembic commands ###
